### ISSUE TITLE
Support Mastodon

### ISSUE THREAD

**Issue by FrittenLoverMarvin** [tech-conferences/conference-data#5670]
What do you think about supporting [Mastodon](https://joinmastodon.org/)?
Many conferences use it additionally to Twitter or as replacement.

![Mastodon](https://github.com/tech-conferences/conference-data/assets/106709454/c7642625-e8cc-4b31-808e-9c8eb106c739)

**Comment by cgrail** [comment]
Sounds reasonable. Should be similar to the following PRs:
https://github.com/tech-conferences/api.confs.tech/commit/218e14fa569a7c34937009b099417fba930c1ae9
https://github.com/tech-conferences/api.confs.tech/commit/850e1c42ada17d75bec05b3e3c03f6552638a157

Because of my missing Rails skills I won't be able to help you.

**Comment by FrittenLoverMarvin** [comment]
Thank you so much for your [P](https://github.com/tech-conferences/confs.tech/pull/564)[R](https://github.com/tech-conferences/api.confs.tech/pull/87)s, @hmasila! 😘

**Comment by nimzco** [comment]
Merged!
