### ISSUE TITLE
Maintainer Role

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6734]
Hello to all the developers of this awesome project!

I've really enjoyed contributing to this project and have learned a lot from the experience. Given my ongoing contributions and my interest in the project's success, I was wondering if I could take on a maintainer role. I believe I can help with the upcoming conference reviews and much more. I'm committed to ensuring high-quality contributions and supporting the project's growth.

Thank you for considering my request.

Best regards,
Juan Diaz

**Comment by cgrail** [comment]
For me it would be ok. What do you think @nimzco

**Comment by cgrail** [comment]
Ok. I've added you to the repo. You should now be able to merge pull requests.

Here are some guidelines I follow:
- add only developer related conferences
- no webinars
- no marketing events
- no hackathons
- no medicine related conferences - we get a lot of PRs for surgery conferences
- a conference must include talks - events like roadshows or conventions without talks are no conferences
- a conference is an event which has at least 3-4 people from different companies. events where only people from company present are not really conferences for me
- shorten the URL as much as possible
- shorten the conference name as much as possible
- check for duplicates before merging
- the conference name should not contain the year or location - not always possible
- check whether the website is reachable
- check whether the CFP page is reachable
- check whether the twitter URL is correct
- check whether the URL is the original URL - we sometimes get PRs where there is a website which adds an advertisement frame around a real conference 
- reorder the conferences using `npm run reorder-confs` from time to time - this prevents ugly merge conflicts
- be careful with merge conflicts - if you're not careful you can delete valid conferences or add removed conferences
- if you add a new location - I usually try to use the US englisch name of the location
- locations in the US must have the state like `San Francisco, CA`
- if you want to add a location which is close to a larger location, I often choose the larger location instead. For example if a conference is close to Detroit, I would rather change the conference location to Detroit than adding a small suburb of Detroit. It's not always simple - in case of doubt you can also ask me
- If you have a conference for multiple topics and you want to change details, you need to adapt the details for all topics
- The topic general should be used alone - I would not mix JAVA and General. It's either or.
- Don't add topics too easy - people sometimes ask to add frameworks or libraries. You need to adapt at least 3-4 places in different projects to add a new topic. It's not that simple.
- don't merge a PR if the checks fail
- run `npm run test` before pushing
- try to keep the test script as fast as possible. Currently the runtime is about 100-200ms
- If you commit/push directly instead of using the new conference form run `npm run reorder-confs` before pushing to avoid merge conflicts.

It think that's all for now. Have fun merging and welcome to the team.

**Comment by JuanPabloDiaz** [comment]
Thanks so much @cgrail and @nimzco! I'm really excited to jump in and help out with maintaining the conference reviews.  This looks like a comprehensive list of guidelines, I'll make sure to review them thoroughly.

**Comment by JuanPabloDiaz** [comment]
I'd appreciate it if I could be added to the notification list for conference form submissions. This would allow me to respond to inquiries and requests from potential conference participants more quickly and efficiently.

**Comment by nimzco** [comment]
> I'd appreciate it if I could be added to the notification list for conference form submissions. This would allow me to respond to inquiries and requests from potential conference participants more quickly and efficiently.

You just need to watch the repo and you'll get notifications for all new contributions :) 

<img width="623" alt="image" src="https://github.com/tech-conferences/conference-data/assets/445045/5ee8b6c3-b70b-407f-a2ef-14a484bb078c">

**Comment by JuanPabloDiaz** [comment]
That's very helpful information, thank you for sharing it.
